# Generated by Django 6.1.1 on 2026-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('category', models.CharField(choices=[('LANZAMIENTOS', 'LANZAMIENTOS'), ('INDUSTRIA', 'INDUSTRIA'), ('EVENTOS', 'EVENTOS'), ('ACTUALIZACIONES', 'ACTUALIZACIONES')], max_length=20, verbose_name='Categoría')),
                ('image', models.ImageField(upload_to='mynews')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
